/**
 * scripts/extract-pages.js
 * Phase 1 — Page Content Extraction
 *
 * Extracts content for each virtual page from the monolithic index.html
 * and saves them as page source templates in src/pages/.
 *
 * The extracted content is the raw HTML between:
 *   <div id="page-X" class="page">
 * and the closing </div> of that block.
 *
 * These source templates are used by scripts/build.js to generate
 * the production multi-page HTML files.
 *
 * NOTE: The extracted content still references go() for navigation.
 * Phase 3 and later phases will update links to use real <a href> navigation.
 *
 * Usage:
 *   node scripts/extract-pages.js
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT     = path.join(__dirname, '..');
const SRC      = path.join(ROOT, 'index.html');
const OUT_DIR  = path.join(ROOT, 'src', 'pages');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

ensureDir(OUT_DIR);

const html = fs.readFileSync(SRC, 'utf8');

// Page boundaries: [pageId, srcFilename, extractionNote]
const pages = [
  { id: 'home',       file: 'home.html',          starts: 'id="page-home"',       ends: 'id="page-about"' },
  { id: 'about',      file: 'about.html',          starts: 'id="page-about"',      ends: 'id="page-capabilities"' },
  { id: 'capabilities', file: 'capabilities.html', starts: 'id="page-capabilities"', ends: 'id="page-blog"' },
  { id: 'blog',       file: 'case-studies.html',   starts: 'id="page-blog"',       ends: 'id="page-portfolio"' },
  { id: 'portfolio',  file: 'portfolio.html',       starts: 'id="page-portfolio"',  ends: 'id="page-career"' },
  { id: 'career',     file: 'career.html',          starts: 'id="page-career"',     ends: 'id="page-contact"' },
  { id: 'contact',    file: 'contact.html',         starts: 'id="page-contact"',    ends: 'id="page-labs"' },
  { id: 'labs',       file: 'labs.html',            starts: 'id="page-labs"',       ends: 'id="page-kritexaai"' },
  { id: 'kritexaai',  file: 'kritexa-ai.html',      starts: 'id="page-kritexaai"',  ends: '</body>' }
];

pages.forEach(function(page, i) {
  const startIdx = html.indexOf('<div ' + page.starts);
  if (startIdx === -1) {
    console.warn('  ⚠ Could not find start for: ' + page.id);
    return;
  }

  var endStr = page.ends === '</body>' ? '</body>' : '<div ' + page.ends;
  var endIdx = html.indexOf(endStr, startIdx);
  if (endIdx === -1) {
    console.warn('  ⚠ Could not find end for: ' + page.id);
    return;
  }

  // Extract the page's <div ...> block
  // Find the last </div>\n\n before the next page start
  var rawContent = html.substring(startIdx, endIdx).trimEnd();

  // Strip the outer <div id="page-X" class="page"> wrapper
  // (In the new architecture each page has its own HTML file, no .page wrapper)
  var innerStart = rawContent.indexOf('>') + 1;
  var inner = rawContent.substring(innerStart).trimStart();
  // Remove trailing </div> from the page wrapper
  if (inner.endsWith('</div>')) {
    inner = inner.substring(0, inner.length - 6).trimEnd();
  }

  var header = '<!-- ══════════════════════════════════════════════════════\n' +
               '  SOURCE TEMPLATE: src/pages/' + page.file + '\n' +
               '  Phase 1 — Extracted from legacy index.html\n' +
               '  Original page ID: #page-' + page.id + '\n' +
               '\n' +
               '  IMPORTANT: This content was extracted verbatim from the\n' +
               '  monolithic index.html. It still contains legacy go()\n' +
               '  navigation calls. These will be updated in Phases 3+.\n' +
               '\n' +
               '  Do not edit this file directly — future phases will\n' +
               '  rewrite it with proper multi-page architecture.\n' +
               '══════════════════════════════════════════════════════ -->\n\n';

  var outPath = path.join(OUT_DIR, page.file);
  fs.writeFileSync(outPath, header + inner + '\n');
  console.log('  ✓ src/pages/' + page.file + '  (' + (Buffer.byteLength(inner, 'utf8') / 1024).toFixed(1) + ' KB)');
});

console.log('\n  Page extraction complete.');
